from __future__ import annotations

import enum


class DocumentStatus(enum.StrEnum):
    RECEBIDO = "RECEBIDO"
    TRIADO = "TRIADO"
    PROCESSADO = "PROCESSADO"
    RASCUNHO_GERADO = "RASCUNHO_GERADO"
    EM_REVISAO = "EM_REVISAO"
    APROVADO = "APROVADO"
    REPROVADO = "REPROVADO"
    CORRIGIDO = "CORRIGIDO"
    FINALIZADO_VALIDADO = "FINALIZADO_VALIDADO"
    PUBLICADO_BUCKET = "PUBLICADO_BUCKET"
    CANCELADO = "CANCELADO"
    SUBSTITUIDO = "SUBSTITUIDO"
    ERRO_PROCESSAMENTO = "ERRO_PROCESSAMENTO"


FINAL_PUBLISH_STATUSES = frozenset({DocumentStatus.APROVADO, DocumentStatus.FINALIZADO_VALIDADO})

SCHEMA_VERSION = "1.0"
GENERATED_BY = "backend-construtora-agentos"
